- hosts: ambari-server
  become: true
  tasks:
  - include: ../../roles/ambari-server/tasks/run-ambari-manager-command.yml
    vars:
      additional_params: --service {{ service_name }} --action stop